### ISSUE TITLE
Commit hook for pytest

### ISSUE THREAD

**Issue by chritter** [StatCan/datascience-cookiecutter#7]
Hello,

It would potentially be beneficial to add a pre-commit hook for pytest. I am currently the following hook for a kaggle competition. If there is consent I would provide a PR.

```
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest kaggle_petals_metal # < its my "src" directory renamed
        language: system
        pass_filenames: false
        always_run: true
        args: ['-v']
```

What do you think @goatsweater @ToucheSir ?
